### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by waltershub** [danielkalbasi/react-native-power-translator#4]
the transaltions in my app were working fine untill this afternoon and now I am getting unhandled promise rejections, my google api is still working  "type Error undefined is not an object 'translation.data.translation"

**Comment by danielkalbasi** [comment]
Hmm that's most probably is from your own code. 

I just tested with the latest Expo and RN and it works fine.

**Comment by MssMaster** [comment]
facing same issue using following versions :

**Comment by phil4lif** [comment]
I am suddenly facing this same issue.  Everything was translating just fine until today.  @waltershub @MssMaster Did either of you ever fix your issue?

**Comment by phil4lif** [comment]
I added some logging in the source code of the package and found that my error is actually that we're exceeding the rate limit, and today everything seems to be working normally again.
